name: do_an_tot_nghiep
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.18.5 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.5
  horizontal_data_table: ^4.1.2+2
  play_kit: ^0.0.2
  date_time_picker: ^2.1.0
  responsive_sizer: ^3.1.0
  table_calendar: ^3.0.7
  intl: ^0.17.0
  date_format: ^2.0.7
  responsive_framework: ^0.2.0
  desktop_drop: ^0.3.3
  dotted_border: ^2.0.0+2
  camera: ^0.10.0+3
  dio: ^4.0.6
  file_picker: ^5.2.0+1
  image_picker: ^0.8.5+3
  image_compression: ^1.0.3
  image_picker_web: ^2.1.1
  image_cropper: ^3.0.0
  flutter_web_data_table: ^1.0.0
  flutter_datetime_picker: ^1.5.1
  qr_flutter: ^4.0.0
  fl_chart: ^0.36.1
  firebase_storage: ^11.0.14
  firebase_core: ^2.7.0
  flutter_spinkit: ^5.1.0
  slide_digital_clock: ^1.0.0
  simple_animations: ^4.1.0
  pin_code_fields: ^7.4.0
  supercharged: ^2.1.1
  dropdown_button2: ^1.9.2
  syncfusion_flutter_xlsio: ^20.3.59-beta
  excel: ^2.0.4
  path_provider: ^2.0.3
  flutter_staggered_animations: ^1.0.0
  multi_select_flutter: ^4.1.3
  flutter_multi_select_items: ^0.4.2
  jwt_decoder: ^2.0.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build_web_compilers: ^3.2.2
  build: ^2.2.1
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - data/
    - data/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
